---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: posts
  label: site/content/posts
  create: all
  match: "**/*"
  templates:
  - posts
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.37.1
